config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'
  get '/signup', to: 'chefs#new'

  resources :recipes do
    resources :comments, only: [:create]
  end
  
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :ingredients, except: [:destroy]
  
  mount ActionCable.server => '/cable'
  
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
  resources :ratings, only: [:update]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  belongs_to :chef
  validates :chef_id, presence: true
  default_scope -> { order(updated_at: :desc) }
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  
  def average_rating
    if ratings.size==0
      0
    else
      ratings.sum(:rate) / ratings.size
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :set_recipe, only: [:show, :update, :edit, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    if logged_in?
      @rating = Rating.where(recipe_id: @recipe.id, chef_id: current_chef.id).first
      unless @rating
        @rating = Rating.create!(recipe_id: @recipe.id, chef_id: current_chef.id, rate: 0)
      end
    end
    @comment = Comment.new
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe saved!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe updated correctly!"
      redirect_to recipe_path(@recipe)
    else
      render "edit"
    end
  end
  
  def destroy
    set_recipe.destroy
    flash[:success] = "Recipe deleted!"
    redirect_to recipes_path
  end
  
  private
  
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
  
  def recipe_params
    params.require(:recipe).permit(:name, :description, ingredient_ids: [])
  end
  
  def require_same_user
    if @recipe.chef != current_chef and !current_chef.admin?
      flash[:danger] = "You are allowed to delete and edit recipes that belong to you!"
      redirect_to recipes_path
    end
  end
end

app/views/recipes/_new_edit.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name of recipe', autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: 'Enter steps to create a recipe' %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
           <%= f.submit class: 'btn btn-primary btn-lg btn-xlarge' %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
    <% if @chef.blank? %>
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </section>
    </div>
    <% end %>
    <div class="col-md-8 <%= @chef.present? ? "col-md-offset-2" : "" %> well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= truncate(recipe.description, length: 150) %></p>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname.capitalize %>
        | <%= pluralize(recipe.comments.count, 'Comment')%> | Rating: </small></span>
      </p>
      <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
        <div class="recipe-actions">
          <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
          <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit a recipe' %>
<%= render 'new_edit' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: 'Showing all recipes' %>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'Create a new recipe' %>
<%= render 'new_edit' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr />
  <%= simple_format(@recipe.description) %>
  <hr />
  <% if @recipe.ingredients.any? %>
    <p>Ingredients: <%= render @recipe.ingredients %></p>
  <% end %>
  <div class="pull-right">
    <p class="center">
      <em>Created by:</em>
    </p>
    <p class="center"><%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %></p>
    <p class="center"><small><%= @recipe.chef.chefname %></small></p>
    <div class="pull-right">
      <%= time_ago_in_words(@recipe.created_at) %> ago
    </div>
  </div>
  <div class="recipe-actions">
    <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
      <%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-xs btn-warning" %>
      <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "Back to index", recipes_path, class: "btn btn-xs btn-info" %>
  </div>
  <div class="pull-left">
    <p class="center">
      Average rating:
    </p>
    <div id="star"></div>
    <% if logged_in? %>
      <p class="center">
        Your rating:
      </p>
      <div id="user_star"></div>
    <% end %>
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments:</h3>
      <hr />
      <%= form_for([@recipe, @comment], remote: true, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: 'Comment this recipe' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
             <%= f.submit "Submit Comment", class: 'btn btn-primary btn-lg btn-xlarge' %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>
<% end %>

<% if @recipe.comments.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <h3>Comments:</h3>
    <div id="messages">
      <%= render partial: 'comments/comments', object: @comments %>
    </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No comments yet</h3>
    </div>
  </div>
<% end %>
<script>
  $('#star').raty({
    readOnly: true,
    score: <%= @recipe.average_rating %>,
    path: '/assets/ratyrate'
  });
  <% if logged_in? %>
    $('#user_star').raty({
      score: <%= @rating.rate %>,
      path: '/assets/ratyrate',
      click: function(score, evt) {
        $.ajax({
          url: '/ratings/' + <%= @rating.id %>,
          type: 'PATCH',
          data: { score: score }
        });
      }
    });
  <% end %>
</script>